#ifndef __BASE_NAMESPACE_H
#define __BASE_NAMESPACE_H

#define BASE_NAMESPACE_BEGIN_DECL				namespace BASEOBJECT {
#define	BASE_NAMESPACE_END_DECL					}

#define BASE_NAMEPSACE_DECL						BASEOBJECT		

#define BASE									BASEOBJECT
#endif
