#include "rudp/rudp_segment.h"

BASE_NAMESPACE_BEGIN_DECL

ObjectPool<RUDPSendSegment, RUDP_SEGMENT_POOL_SIZE>	SENDSEGPOOL;
ObjectPool<RUDPRecvSegment, RUDP_SEGMENT_POOL_SIZE>	RECVSEGPOOL;

BASE_NAMESPACE_END_DECL